os: windows
language: cpp
compiler: g++
install:
  - cd ./tests/cxxtest/bin
  - python ./cxxtestgen --error-printer -o ../../runner.cpp ../../tests.h
  - cd .. && cd ..
script:
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/" -fconcepts
  - ls -l ./
  - runner.exe
