os: linux
language: cpp
compiler: g++
install: skip
sudo: required
script:
  - set -e
  - sudo dpkg --add-architecture i386
  - wget -nc https://dl.winehq.org/wine-builds/winehq.key
  - sudo apt-key add winehq.key
  - echo "deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main" >> /etc/apt/sources.list
  - sudo apt update
  - sudo apt install --install-recommends winehq-stable
  - winecfg
  - cd ./tests
  - cd ./cxxtest/bin
  - python ./cxxtestgen --error-printer -o ../../runner.cpp ../../tests.h
  - cd ..
  - cd ..
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/" -std=c++11 -std=c++14
  - wine ./runner.exe
