os: linux
language: cpp
compiler: g++
install: skip
sudo: required
script:
  - set -e
  - sudo apt-get install wine
  - cd ./tests
  - cd ./cxxtest/bin
  - wine ./cxxtestgen --error-printer -o ../../runner.cpp ../../tests.h
  - cd ..
  - cd ..
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/" -fconcepts
  - wine ./runner.exe
