os: windows
language: cpp
compiler: g++
install: skip
script:
  - set -e
  - cd ./tests
  - cd ./cxxtest/bin
  - start cxxtestgen --error-printer -o runner.cpp ../../tests.h
  - cd ..
  - cd ..
  - move ./cxxtest/bin/runner.cpp ./
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/" -fconcepts
  - start /wait cmd /c runner.exe
