os: windows
language: cpp
compiler: g++
install: skip
script:
  - cd ./tests
  - cd ./cxxtest/bin
  - cxxtestgen --error-printer -o ../../runner.cpp ../../tests.h
  - cd ..
  - cd ..
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/"
  - call runner.exe
