os: windows
language: cpp
compiler: g++
install:
  - set -e
  - cd ./tests
  - cd ./cxxtest/bin
  - python ./cxxtestgen --error-printer -o ../../runner.cpp ../../tests.h
  - cd ..
  - cd ..
  - dir
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/" -fconcepts
script:
  - ./runner.exe
