os: windows
language: cpp
compiler: g++
powershell: 
install:
  - cd ./tests/cxxtest/bin
  - python ./cxxtestgen --error-printer -o ../../runner.cpp ../../tests.h
  - cd .. && cd ..
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/" -fconcepts
script:
  - & "./runner.exe"
