os: windows
language: cpp
compiler: g++
install: skip
script:
  - cd ./tests
  - cd ./cxxtest/bin
  - start /wait cxxtestgen --error-printer -o ../../runner.cpp ../../tests.h
  - cd ..
  - cd ..
  - dir
  - g++ runner.cpp -o runner.exe -I"./cxxtest/" -I"../src/" -fconcepts
  - start /wait runner.exe
